-- FTC-GUID: 64a91b
    -- TO CHANGE THE SIZE OF THE AREA FOR THE MAP LOADING/DELETING, READ THIS
    -- Change the zoneScale size to match a zone you create in game (as reference)
    -- Be sure the zone extends below the table too
    -- This should be the same as the Saving Tool for your table.
    -------------------------------------------------------------
    zoneScale = {x=60.12, y=73, z=44.04} --60x44 Strike Force
    -------------------------------------------------------------
    function onLoad()
        self.createButton({
            label = "Load Map",
            font_size = 115,
            color = {0, 1, 0,},
            position = {-0.96, 0.5, 0},
            rotation = {0, 90, 0},
            scale = {1.3, 1, .7},
            width = 570,
            height = 160,
            click_function = "loadMap",
            function_owner = self,
        })

        self.createButton({
            label = "Clear Map",
            font_size = 100,
            position = {1, 0.5, 0},
            rotation = {0, 90, 0},
            scale = {.6, .6, .4},
            width = 530,
            height = 130,
            color = {1, 0, 0},
            click_function = "clearMap",
            function_owner = self,
        })
    end

    -------------------
    -- Prepares the terrain saved into the card from Map Saver tool
    string.split = function(s, delimiter)
        local result = { }
        local from  = 1
        local delim_from, delim_to = string.find( s, delimiter, from  )
        while delim_from do
            table.insert( result, string.sub( s, from , delim_from-1 ) )
            from  = delim_to + 1
            delim_from, delim_to = string.find( s, delimiter, from  )
        end
        table.insert( result, string.sub( s, from  ) )
        return result
    end

	function scriptzoneCallback(zone) --This deletes everything except the things listed, when the scripting zone is briefly spawned.

        local objects = zone.getObjects()

        for i, obj in ipairs(objects) do
            ----------------------------------------------
             --IMPORTANT! Keep the map card from deleting speficic stuff here
            ----------------------------------------------
            if obj.getGMNotes() ~= "MapExclude" -- As black player, right click and add "MapExclude" to anything you dont want deleted. You may have to temporarily make your table interactable to do this, with its scripting.
                and
                obj.getGUID() ~= "e7ca6e" --Exclude Map Buidler Table
                and
                obj.getGUID() ~= "6012bf" --...and ForceOrg Table...
                and
                obj.getGUID() ~= "4ee1f2" --...and FTC board matObjSurface
                and
                obj.getGUID() ~= "948ce5" --...and FTC Table
                and
                obj.getGUID() ~= "28865a" --...and FTC Felt Surface
                then
                obj.destruct()
            end
        end
        zone.destruct()
    end
    function loadMap(objectClicked, clickerColor, altClickUsed)
        ----------
        -- Spawn the scripting zone, which uses the callback above that deletes everything then deletes itself.
        local scriptzoneParams = {                  -- Define the parameters for the scripting zone
            position = {x=0, y=26, z=0},
            scale = zoneScale,
            type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
            callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
            callback_owner = self,
            }

		spawnObject(scriptzoneParams)
		-- Then Sspawn the objects stored in the card

        Wait.time(
        function()
            for _, objectJSON in ipairs(objectJSONs) do
                -- Spawn the map from the JSON data
                spawnObjectJSON({
                    json = objectJSON
                })
            end
        end, .5)
    end

    -----------------------------
    -- This function runs when the Clear Map button is clicked on the Map Card
    function clearMap(objectClicked, clickerColor, altClickUsed)

        local scriptzoneParams = {                  -- Define the parameters for the scripting zone
            position = {x=0, y=26, z=0},
            scale = zoneScale,
            type = 'ScriptingTrigger',              -- Use the ScriptingTrigger type to spawn a Scripting Zone
            callback_function = scriptzoneCallback, -- Specify the function to call when the zone is created
            callback_owner = self,
            }

    spawnObject(scriptzoneParams)

    end


objectJSONs = {
  [[{
  "GUID": "d3288d",
  "Name": "Custom_Model",
  "Transform": {
    "posX": 12.9999981,
    "posY": 1.118886,
    "posZ": 7.999997,
    "rotX": 1.3713754E-05,
    "rotY": 180.004028,
    "rotZ": -4.53084368E-07,
    "scaleX": 1.0,
    "scaleY": 1.0,
    "scaleZ": 1.0
  },
  "Nickname": "CORNER RUIN",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
    "NormalURL": "",
    "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 0,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "States": {
    "2": {
      "GUID": "a9e434",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -1.26980686,
        "posY": 1.0781014,
        "posZ": -3.73181868,
        "rotX": 1.48279241E-05,
        "rotY": 359.862061,
        "rotZ": -3.28164924E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "CORNER RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "001282",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.8854872,
            "posY": -0.01889487,
            "posZ": -0.903949142,
            "rotX": 0.0489747748,
            "rotY": 89.9732,
            "rotZ": 359.8637,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.0
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997848975584/F51A04B8EE4DE4A3CF076D563674FCDDE89E4908/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  },
  "ChildObjects": [
    {
      "GUID": "7a0649",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -2.73106527,
        "posY": 3.262319,
        "posZ": -2.51815367,
        "rotX": 0.00368775474,
        "rotY": 269.9999,
        "rotZ": 0.00301319058,
        "scaleX": 0.999999762,
        "scaleY": 1.0,
        "scaleZ": 0.999999762
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068390/F02B8BEF7FD81C51B55E37CDD86DC4D973EE3CD9/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068390/F02B8BEF7FD81C51B55E37CDD86DC4D973EE3CD9/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "001282",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 1.61403477,
            "posY": -3.28141761,
            "posZ": -1.84536421,
            "rotX": 0.0526639,
            "rotY": 179.973236,
            "rotZ": 359.86673,
            "scaleX": 0.999999762,
            "scaleY": 1.0,
            "scaleZ": 0.9999999
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997848975584/F51A04B8EE4DE4A3CF076D563674FCDDE89E4908/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "a415af",
  "Name": "Custom_Model",
  "Transform": {
    "posX": 17.99983,
    "posY": 1.14656234,
    "posZ": 2.99996161,
    "rotX": 0.000395890849,
    "rotY": 270.009674,
    "rotZ": 0.132366121,
    "scaleX": 1.0,
    "scaleY": 1.0,
    "scaleZ": 1.0
  },
  "Nickname": "THREE STOREY RUIN",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
    "NormalURL": "",
    "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 0,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "States": {
    "3": {
      "GUID": "b20d2b",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.8200669,
        "posY": 1.07810259,
        "posZ": -3.081963,
        "rotX": 2.22451617E-05,
        "rotY": 0.0108686965,
        "rotZ": 1.72115381E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "THREE STOREY RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "82f221",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.985774,
            "posY": -0.0167070255,
            "posZ": -0.6786437,
            "rotX": 0.115770482,
            "rotY": 225.0009,
            "rotZ": 359.96698,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.0
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    },
    "2": {
      "GUID": "6dedb9",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.8200655,
        "posY": 1.07810235,
        "posZ": -3.08196259,
        "rotX": 2.27142082E-05,
        "rotY": 0.01085749,
        "rotZ": 1.16358456E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "THREE STOREY RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "94dc26",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.97873259,
            "posY": 3.2045126,
            "posZ": -4.21821356,
            "rotX": -0.0002799229,
            "rotY": 314.999969,
            "rotZ": 0.0005063273,
            "scaleX": 0.99999994,
            "scaleY": 1.0,
            "scaleZ": 0.99999994
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "6b2715",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.985772,
            "posY": -0.0166705865,
            "posZ": -0.678638458,
            "rotX": 0.116295509,
            "rotY": 225.000931,
            "rotZ": 359.967255,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.00000012
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  },
  "ChildObjects": [
    {
      "GUID": "bfc8d4",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -5.78073454,
        "posY": 6.13451,
        "posZ": -2.888816,
        "rotX": 0.0008904774,
        "rotY": 314.967,
        "rotZ": -0.0010958768,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068562/AB3C4C85583BBE02BD556241F641106DF23C26BF/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068562/AB3C4C85583BBE02BD556241F641106DF23C26BF/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "6b2715",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 1.41894877,
            "posY": -6.15116453,
            "posZ": 1.70709622,
            "rotX": 0.116865523,
            "rotY": 270.033875,
            "rotZ": 359.967865,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 0.9999999
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "94dc26",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -1.0804044,
            "posY": -2.93003225,
            "posZ": -0.7993355,
            "rotX": -0.000872467353,
            "rotY": 0.032894183,
            "rotZ": 0.00107640936,
            "scaleX": 1.00000012,
            "scaleY": 1.0,
            "scaleZ": 1.00000012
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "7f414f",
  "Name": "Custom_Model",
  "Transform": {
    "posX": 0.0019,
    "posY": -10.13,
    "posZ": 0.0029,
    "rotX": 0.0,
    "rotY": 0.0,
    "rotZ": 0.0,
    "scaleX": 1.666,
    "scaleY": 1.06,
    "scaleZ": 1.2206
  },
  "Nickname": "",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": true,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/879750610978796176/4A5A65543B98BCFBF57E910D06EC984208223D38/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2446098699627521010/47C1C9B6EC3FFE187F09303E8F44D36FF0E8D541/",
    "NormalURL": "",
    "ColliderURL": "",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 4,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "function onload() \r\n    self.interactable = false\r\n    self.gizmo_selectable = true\r\nend",
  "LuaScriptState": "",
  "XmlUI": ""
}]],
  [[{
  "GUID": "b7a02f",
  "Name": "Custom_Model",
  "Transform": {
    "posX": -17.99983,
    "posY": 1.12617421,
    "posZ": -2.99996161,
    "rotX": 0.0003958975,
    "rotY": 90.00968,
    "rotZ": 0.1323658,
    "scaleX": 1.0,
    "scaleY": 1.0,
    "scaleZ": 1.0
  },
  "Nickname": "THREE STOREY RUIN",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
    "NormalURL": "",
    "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 0,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "States": {
    "3": {
      "GUID": "b20d2b",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.8200669,
        "posY": 1.07810259,
        "posZ": -3.081963,
        "rotX": 2.22451617E-05,
        "rotY": 0.0108686965,
        "rotZ": 1.72115381E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "THREE STOREY RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "82f221",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.985774,
            "posY": -0.0167070255,
            "posZ": -0.6786437,
            "rotX": 0.115770482,
            "rotY": 225.0009,
            "rotZ": 359.96698,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.0
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    },
    "2": {
      "GUID": "6dedb9",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.8200655,
        "posY": 1.07810235,
        "posZ": -3.08196259,
        "rotX": 2.27142082E-05,
        "rotY": 0.01085749,
        "rotZ": 1.16358456E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "THREE STOREY RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "94dc26",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.97873259,
            "posY": 3.2045126,
            "posZ": -4.21821356,
            "rotX": -0.0002799229,
            "rotY": 314.999969,
            "rotZ": 0.0005063273,
            "scaleX": 0.99999994,
            "scaleY": 1.0,
            "scaleZ": 0.99999994
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "6b2715",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.985772,
            "posY": -0.0166705865,
            "posZ": -0.678638458,
            "rotX": 0.116295509,
            "rotY": 225.000931,
            "rotZ": 359.967255,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.00000012
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  },
  "ChildObjects": [
    {
      "GUID": "bfc8d4",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -5.78073454,
        "posY": 6.13451,
        "posZ": -2.888816,
        "rotX": 0.0008904774,
        "rotY": 314.967,
        "rotZ": -0.0010958768,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068562/AB3C4C85583BBE02BD556241F641106DF23C26BF/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068562/AB3C4C85583BBE02BD556241F641106DF23C26BF/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "6b2715",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 1.41894877,
            "posY": -6.15116453,
            "posZ": 1.70709622,
            "rotX": 0.116865523,
            "rotY": 270.033875,
            "rotZ": 359.967865,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 0.9999999
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "94dc26",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -1.0804044,
            "posY": -2.93003225,
            "posZ": -0.7993355,
            "rotX": -0.000872467353,
            "rotY": 0.032894183,
            "rotZ": 0.00107640936,
            "scaleX": 1.00000012,
            "scaleY": 1.0,
            "scaleZ": 1.00000012
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "45f4ba",
  "Name": "Custom_Model",
  "Transform": {
    "posX": -12.9999981,
    "posY": 1.09849787,
    "posZ": -7.999997,
    "rotX": 1.3713754E-05,
    "rotY": 0.004034747,
    "rotZ": -4.53084368E-07,
    "scaleX": 1.0,
    "scaleY": 1.0,
    "scaleZ": 1.0
  },
  "Nickname": "CORNER RUIN",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
    "NormalURL": "",
    "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 0,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "States": {
    "2": {
      "GUID": "a9e434",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -1.26980686,
        "posY": 1.0781014,
        "posZ": -3.73181868,
        "rotX": 1.48279241E-05,
        "rotY": 359.862061,
        "rotZ": -3.28164924E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "CORNER RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "001282",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -0.8854872,
            "posY": -0.01889487,
            "posZ": -0.903949142,
            "rotX": 0.0489747748,
            "rotY": 89.9732,
            "rotZ": 359.8637,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.0
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997848975584/F51A04B8EE4DE4A3CF076D563674FCDDE89E4908/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  },
  "ChildObjects": [
    {
      "GUID": "7a0649",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -2.73106527,
        "posY": 3.262319,
        "posZ": -2.51815367,
        "rotX": 0.00368775474,
        "rotY": 269.9999,
        "rotZ": 0.00301319058,
        "scaleX": 0.999999762,
        "scaleY": 1.0,
        "scaleZ": 0.999999762
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068390/F02B8BEF7FD81C51B55E37CDD86DC4D973EE3CD9/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068390/F02B8BEF7FD81C51B55E37CDD86DC4D973EE3CD9/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "001282",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 1.61403477,
            "posY": -3.28141761,
            "posZ": -1.84536421,
            "rotX": 0.0526639,
            "rotY": 179.973236,
            "rotZ": 359.86673,
            "scaleX": 0.999999762,
            "scaleY": 1.0,
            "scaleZ": 0.9999999
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997848975584/F51A04B8EE4DE4A3CF076D563674FCDDE89E4908/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "d6f0e0",
  "Name": "Custom_Model",
  "Transform": {
    "posX": -6.99999666,
    "posY": 1.11888623,
    "posZ": 10.0,
    "rotX": 8.093503E-06,
    "rotY": 89.9908142,
    "rotZ": 3.57802946E-07,
    "scaleX": 1.0,
    "scaleY": 1.0,
    "scaleZ": 1.0
  },
  "Nickname": "CORNER RUIN",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
    "NormalURL": "",
    "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 0,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "States": {
    "2": {
      "GUID": "8f2c02",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 3.69221,
        "posY": 1.0781033,
        "posZ": -3.242485,
        "rotX": 1.33909016E-05,
        "rotY": 0.14827092,
        "rotZ": 5.33851926E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "CORNER RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "001282",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -6.004538,
            "posY": -0.0188955,
            "posZ": -0.526313245,
            "rotX": 0.0489601232,
            "rotY": 44.9731445,
            "rotZ": 359.863739,
            "scaleX": 1.00000012,
            "scaleY": 1.0,
            "scaleZ": 1.0
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997848975584/F51A04B8EE4DE4A3CF076D563674FCDDE89E4908/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  },
  "ChildObjects": [
    {
      "GUID": "7a0649",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -6.16813946,
        "posY": 3.26231885,
        "posZ": -2.972749,
        "rotX": 0.00369668077,
        "rotY": 224.9999,
        "rotZ": 0.00301195774,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068390/F02B8BEF7FD81C51B55E37CDD86DC4D973EE3CD9/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068390/F02B8BEF7FD81C51B55E37CDD86DC4D973EE3CD9/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "001282",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 1.61403477,
            "posY": -3.28141761,
            "posZ": -1.84536421,
            "rotX": 0.0526639,
            "rotY": 179.973236,
            "rotZ": 359.86673,
            "scaleX": 0.999999762,
            "scaleY": 1.0,
            "scaleZ": 0.9999999
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997848975584/F51A04B8EE4DE4A3CF076D563674FCDDE89E4908/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "c30038",
  "Name": "Custom_Model",
  "Transform": {
    "posX": -12.0118952,
    "posY": 3.27580452,
    "posZ": -21.6105537,
    "rotX": 0.0008371969,
    "rotY": 270.018127,
    "rotZ": -6.46649351E-05,
    "scaleX": 0.9000001,
    "scaleY": 0.9000001,
    "scaleZ": 1.03012776
  },
  "Nickname": "CONTAINER",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846707412/7E25A270A9E17782FB9CD609629EC54A4EA98233/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846725160/D84F4480F9D211ED288131ADD8FD31C400A2ED20/",
    "NormalURL": "",
    "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846707412/7E25A270A9E17782FB9CD609629EC54A4EA98233/",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 0,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "e00626",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.127363265,
        "posY": -2.78539419,
        "posZ": 9.109685E-05,
        "rotX": -0.0008366924,
        "rotY": 0.05315406,
        "rotZ": 6.328779E-05,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846707412/7E25A270A9E17782FB9CD609629EC54A4EA98233/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846725160/D84F4480F9D211ED288131ADD8FD31C400A2ED20/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846707412/7E25A270A9E17782FB9CD609629EC54A4EA98233/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "477e22",
  "Name": "Custom_Model",
  "Transform": {
    "posX": -8.999754,
    "posY": 1.117847,
    "posZ": -0.0001707077,
    "rotX": 0.008435627,
    "rotY": 270.000854,
    "rotZ": 0.095462054,
    "scaleX": 1.0,
    "scaleY": 1.0,
    "scaleZ": 1.0
  },
  "Nickname": "THREE STOREY RUIN",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
    "NormalURL": "",
    "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 0,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "States": {
    "3": {
      "GUID": "b20d2b",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.8200669,
        "posY": 1.07810259,
        "posZ": -3.081963,
        "rotX": 2.22451617E-05,
        "rotY": 0.0108686965,
        "rotZ": 1.72115381E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "THREE STOREY RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "82f221",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.985774,
            "posY": -0.0167070255,
            "posZ": -0.6786437,
            "rotX": 0.115770482,
            "rotY": 225.0009,
            "rotZ": 359.96698,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.0
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    },
    "2": {
      "GUID": "6dedb9",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.8200655,
        "posY": 1.07810235,
        "posZ": -3.08196259,
        "rotX": 2.27142082E-05,
        "rotY": 0.01085749,
        "rotZ": 1.16358456E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "THREE STOREY RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "94dc26",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.97873259,
            "posY": 3.2045126,
            "posZ": -4.21821356,
            "rotX": -0.0002799229,
            "rotY": 314.999969,
            "rotZ": 0.0005063273,
            "scaleX": 0.99999994,
            "scaleY": 1.0,
            "scaleZ": 0.99999994
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "6b2715",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.985772,
            "posY": -0.0166705865,
            "posZ": -0.678638458,
            "rotX": 0.116295509,
            "rotY": 225.000931,
            "rotZ": 359.967255,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.00000012
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  },
  "ChildObjects": [
    {
      "GUID": "bfc8d4",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -5.78073454,
        "posY": 6.13451,
        "posZ": -2.888816,
        "rotX": 0.0008904774,
        "rotY": 314.967,
        "rotZ": -0.0010958768,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068562/AB3C4C85583BBE02BD556241F641106DF23C26BF/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068562/AB3C4C85583BBE02BD556241F641106DF23C26BF/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "6b2715",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 1.41894877,
            "posY": -6.15116453,
            "posZ": 1.70709622,
            "rotX": 0.116865523,
            "rotY": 270.033875,
            "rotZ": 359.967865,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 0.9999999
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "94dc26",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -1.0804044,
            "posY": -2.93003225,
            "posZ": -0.7993355,
            "rotX": -0.000872467353,
            "rotY": 0.032894183,
            "rotZ": 0.00107640936,
            "scaleX": 1.00000012,
            "scaleY": 1.0,
            "scaleZ": 1.00000012
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "78e8d4",
  "Name": "Custom_Model",
  "Transform": {
    "posX": 8.999754,
    "posY": 1.13823509,
    "posZ": 0.0001707077,
    "rotX": 0.008435621,
    "rotY": 90.00087,
    "rotZ": 0.095462054,
    "scaleX": 1.0,
    "scaleY": 1.0,
    "scaleZ": 1.0
  },
  "Nickname": "THREE STOREY RUIN",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
    "NormalURL": "",
    "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 0,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "States": {
    "3": {
      "GUID": "b20d2b",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.8200669,
        "posY": 1.07810259,
        "posZ": -3.081963,
        "rotX": 2.22451617E-05,
        "rotY": 0.0108686965,
        "rotZ": 1.72115381E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "THREE STOREY RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "82f221",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.985774,
            "posY": -0.0167070255,
            "posZ": -0.6786437,
            "rotX": 0.115770482,
            "rotY": 225.0009,
            "rotZ": 359.96698,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.0
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    },
    "2": {
      "GUID": "6dedb9",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.8200655,
        "posY": 1.07810235,
        "posZ": -3.08196259,
        "rotX": 2.27142082E-05,
        "rotY": 0.01085749,
        "rotZ": 1.16358456E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "THREE STOREY RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "94dc26",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.97873259,
            "posY": 3.2045126,
            "posZ": -4.21821356,
            "rotX": -0.0002799229,
            "rotY": 314.999969,
            "rotZ": 0.0005063273,
            "scaleX": 0.99999994,
            "scaleY": 1.0,
            "scaleZ": 0.99999994
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "6b2715",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -5.985772,
            "posY": -0.0166705865,
            "posZ": -0.678638458,
            "rotX": 0.116295509,
            "rotY": 225.000931,
            "rotZ": 359.967255,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 1.00000012
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  },
  "ChildObjects": [
    {
      "GUID": "bfc8d4",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -5.78073454,
        "posY": 6.13451,
        "posZ": -2.888816,
        "rotX": 0.0008904774,
        "rotY": 314.967,
        "rotZ": -0.0010958768,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068562/AB3C4C85583BBE02BD556241F641106DF23C26BF/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068562/AB3C4C85583BBE02BD556241F641106DF23C26BF/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "6b2715",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 1.41894877,
            "posY": -6.15116453,
            "posZ": 1.70709622,
            "rotX": 0.116865523,
            "rotY": 270.033875,
            "rotZ": 359.967865,
            "scaleX": 1.0,
            "scaleY": 1.0,
            "scaleZ": 0.9999999
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997847009029/018153E30EC3C9C6BA33D943C6CF85A24E781B77/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        },
        {
          "GUID": "94dc26",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -1.0804044,
            "posY": -2.93003225,
            "posZ": -0.7993355,
            "rotX": -0.000872467353,
            "rotY": 0.032894183,
            "rotZ": 0.00107640936,
            "scaleX": 1.00000012,
            "scaleY": 1.0,
            "scaleZ": 1.00000012
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068637/86B32C728D1A266A905F51457D1A12F09FBFCD42/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],
  [[{
  "GUID": "b94cde",
  "Name": "Custom_Model",
  "Transform": {
    "posX": 3.580577,
    "posY": 3.27580476,
    "posZ": 16.1567783,
    "rotX": 0.0008372264,
    "rotY": 270.001282,
    "rotZ": -6.1978164E-05,
    "scaleX": 0.9000001,
    "scaleY": 0.9000001,
    "scaleZ": 1.03012776
  },
  "Nickname": "CONTAINER",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846707412/7E25A270A9E17782FB9CD609629EC54A4EA98233/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846725160/D84F4480F9D211ED288131ADD8FD31C400A2ED20/",
    "NormalURL": "",
    "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846707412/7E25A270A9E17782FB9CD609629EC54A4EA98233/",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 0,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "ChildObjects": [
    {
      "GUID": "e00626",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 0.127363265,
        "posY": -2.78539419,
        "posZ": 9.109685E-05,
        "rotX": -0.0008366924,
        "rotY": 0.05315406,
        "rotZ": 6.328779E-05,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846707412/7E25A270A9E17782FB9CD609629EC54A4EA98233/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846725160/D84F4480F9D211ED288131ADD8FD31C400A2ED20/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846707412/7E25A270A9E17782FB9CD609629EC54A4EA98233/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": ""
    }
  ]
}]],
  [[{
  "GUID": "1f111b",
  "Name": "Custom_Model",
  "Transform": {
    "posX": 6.99999666,
    "posY": 1.09849811,
    "posZ": -10.0,
    "rotX": 8.093503E-06,
    "rotY": 269.9908,
    "rotZ": 3.57803344E-07,
    "scaleX": 1.0,
    "scaleY": 1.0,
    "scaleZ": 1.0
  },
  "Nickname": "CORNER RUIN",
  "Description": "",
  "GMNotes": "",
  "AltLookAngle": {
    "x": 0.0,
    "y": 0.0,
    "z": 0.0
  },
  "ColorDiffuse": {
    "r": 1.0,
    "g": 1.0,
    "b": 1.0
  },
  "LayoutGroupSortIndex": 0,
  "Value": 0,
  "Locked": true,
  "Grid": true,
  "Snap": true,
  "IgnoreFoW": false,
  "MeasureMovement": false,
  "DragSelectable": true,
  "Autoraise": true,
  "Sticky": true,
  "Tooltip": true,
  "GridProjection": false,
  "HideWhenFaceDown": false,
  "Hands": false,
  "CustomMesh": {
    "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
    "NormalURL": "",
    "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
    "Convex": true,
    "MaterialIndex": 3,
    "TypeIndex": 0,
    "CustomShader": {
      "SpecularColor": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "SpecularIntensity": 0.0,
      "SpecularSharpness": 2.0,
      "FresnelStrength": 0.0
    },
    "CastShadows": true
  },
  "LuaScript": "",
  "LuaScriptState": "",
  "XmlUI": "",
  "States": {
    "2": {
      "GUID": "8f2c02",
      "Name": "Custom_Model",
      "Transform": {
        "posX": 3.69221,
        "posY": 1.0781033,
        "posZ": -3.242485,
        "rotX": 1.33909016E-05,
        "rotY": 0.14827092,
        "rotZ": 5.33851926E-06,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "CORNER RUIN",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": false,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846844435/9541D920768A791724E2D117324631745FDCDC50/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2468612172827588488/D247DEBC3EB3CCB629835C4801DF948CD127DF7F/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "001282",
          "Name": "Custom_Model",
          "Transform": {
            "posX": -6.004538,
            "posY": -0.0188955,
            "posZ": -0.526313245,
            "rotX": 0.0489601232,
            "rotY": 44.9731445,
            "rotZ": 359.863739,
            "scaleX": 1.00000012,
            "scaleY": 1.0,
            "scaleZ": 1.0
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997848975584/F51A04B8EE4DE4A3CF076D563674FCDDE89E4908/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  },
  "ChildObjects": [
    {
      "GUID": "7a0649",
      "Name": "Custom_Model",
      "Transform": {
        "posX": -6.16813946,
        "posY": 3.26231885,
        "posZ": -2.972749,
        "rotX": 0.00369668077,
        "rotY": 224.9999,
        "rotZ": 0.00301195774,
        "scaleX": 1.0,
        "scaleY": 1.0,
        "scaleZ": 1.0
      },
      "Nickname": "",
      "Description": "",
      "GMNotes": "",
      "AltLookAngle": {
        "x": 0.0,
        "y": 0.0,
        "z": 0.0
      },
      "ColorDiffuse": {
        "r": 1.0,
        "g": 1.0,
        "b": 1.0
      },
      "LayoutGroupSortIndex": 0,
      "Value": 0,
      "Locked": true,
      "Grid": true,
      "Snap": true,
      "IgnoreFoW": false,
      "MeasureMovement": false,
      "DragSelectable": true,
      "Autoraise": true,
      "Sticky": true,
      "Tooltip": true,
      "GridProjection": false,
      "HideWhenFaceDown": false,
      "Hands": false,
      "CustomMesh": {
        "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068390/F02B8BEF7FD81C51B55E37CDD86DC4D973EE3CD9/",
        "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719514/A00E59CE37125604175A99216D20D22A82560A08/",
        "NormalURL": "",
        "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997850068390/F02B8BEF7FD81C51B55E37CDD86DC4D973EE3CD9/",
        "Convex": true,
        "MaterialIndex": 3,
        "TypeIndex": 0,
        "CustomShader": {
          "SpecularColor": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "SpecularIntensity": 0.0,
          "SpecularSharpness": 2.0,
          "FresnelStrength": 0.0
        },
        "CastShadows": true
      },
      "LuaScript": "",
      "LuaScriptState": "",
      "XmlUI": "",
      "ChildObjects": [
        {
          "GUID": "001282",
          "Name": "Custom_Model",
          "Transform": {
            "posX": 1.61403477,
            "posY": -3.28141761,
            "posZ": -1.84536421,
            "rotX": 0.0526639,
            "rotY": 179.973236,
            "rotZ": 359.86673,
            "scaleX": 0.999999762,
            "scaleY": 1.0,
            "scaleZ": 0.9999999
          },
          "Nickname": "",
          "Description": "",
          "GMNotes": "",
          "AltLookAngle": {
            "x": 0.0,
            "y": 0.0,
            "z": 0.0
          },
          "ColorDiffuse": {
            "r": 1.0,
            "g": 1.0,
            "b": 1.0
          },
          "LayoutGroupSortIndex": 0,
          "Value": 0,
          "Locked": true,
          "Grid": true,
          "Snap": true,
          "IgnoreFoW": false,
          "MeasureMovement": false,
          "DragSelectable": true,
          "Autoraise": true,
          "Sticky": true,
          "Tooltip": true,
          "GridProjection": false,
          "HideWhenFaceDown": false,
          "Hands": false,
          "CustomMesh": {
            "MeshURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997848975584/F51A04B8EE4DE4A3CF076D563674FCDDE89E4908/",
            "DiffuseURL": "https://steamusercontent-a.akamaihd.net/ugc/2504633997846719713/CFC02C3429562C5534009E8A7FA0314B226E64BF/",
            "NormalURL": "",
            "ColliderURL": "https://steamusercontent-a.akamaihd.net/ugc/1723164938912201570/3CFC9BAA671D43615F4A56A37B443F1819EA1672/",
            "Convex": true,
            "MaterialIndex": 3,
            "TypeIndex": 0,
            "CustomShader": {
              "SpecularColor": {
                "r": 1.0,
                "g": 1.0,
                "b": 1.0
              },
              "SpecularIntensity": 0.0,
              "SpecularSharpness": 2.0,
              "FresnelStrength": 0.0
            },
            "CastShadows": true
          },
          "LuaScript": "",
          "LuaScriptState": "",
          "XmlUI": ""
        }
      ]
    }
  ]
}]],

}

